import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import NextUiProvider from "@/components/NextUIProvider/NextUIProvider";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} -mt-[4.04rem]`}>
        <Toaster/>
        <Navbar/>
        <NextUiProvider>
          <main className="flex flex-col max-w-[1440px] mx-auto">
            {children}
          </main>
        </NextUiProvider>
      </body>
    </html>
  );
}
